fn main() {
    generate_build_info();

    let target_os = std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    if target_os != "windows" {
        return;
    }

    let version = std::env::var("CARGO_PKG_VERSION").unwrap_or_else(|_| "0.0.0".into());
    let version_parts: Vec<u32> = version.split('.').filter_map(|p| p.parse().ok()).collect();
    let v_major = version_parts.first().copied().unwrap_or(0);
    let v_minor = version_parts.get(1).copied().unwrap_or(0);
    let v_patch = version_parts.get(2).copied().unwrap_or(0);

    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap_or_else(|_| ".".into());
    let icon_path = format!("{manifest_dir}/icons/icon.ico");
    // Numeric FILEVERSION/PRODUCTVERSION mirror the SemVer (PRD §37): build
    // timestamps or commits never substitute the numeric fields. The UI
    // shows "0.9.0"; diagnostics show "0.9.0 + commit" via BuildInfo.
    let rc_content = format!(
        r#"1 ICON "{icon_path}"

1 VERSIONINFO
FILEVERSION {v_major},{v_minor},{v_patch},0
PRODUCTVERSION {v_major},{v_minor},{v_patch},0
FILEFLAGSMASK 0x3fL
FILEFLAGS 0x0L
FILEOS 0x40004L
FILETYPE 0x1L
FILESUBTYPE 0x0L
BEGIN
    BLOCK "StringFileInfo"
    BEGIN
        BLOCK "080404b0"
        BEGIN
            VALUE "CompanyName", "LogcatX"
            VALUE "FileDescription", "LogcatX - multi-device adb logcat GUI"
            VALUE "FileVersion", "{v_major}.{v_minor}.{v_patch}.0"
            VALUE "InternalName", "logcatx"
            VALUE "OriginalFilename", "LogcatX.exe"
            VALUE "ProductName", "LogcatX"
            VALUE "ProductVersion", "{version}"
        END
    END
    BLOCK "VarFileInfo"
    BEGIN
        VALUE "Translation", 0x0804, 1200
    END
END
"#
    );

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let rc_path = format!("{out_dir}/resource.rc");
    std::fs::write(&rc_path, &rc_content).expect("failed to write generated rc file");

    println!("cargo:rerun-if-env-changed=RC");
    let rc = std::env::var("RC")
        .ok()
        .and_then(|found| normalize_which_path(&found))
        .map(|path| ResourceCompiler::from_path(path, ResourceCompilerKind::Microsoft))
        .or_else(|| {
            which("llvm-rc")
                .and_then(|found| normalize_which_path(&found))
                .map(|path| ResourceCompiler::from_path(path, ResourceCompilerKind::Llvm))
        })
        .or_else(|| {
            which("llvm-rc-20")
                .and_then(|found| normalize_which_path(&found))
                .map(|path| ResourceCompiler::from_path(path, ResourceCompilerKind::Llvm))
        })
        .or_else(find_windows_sdk_rc);

    let Some(rc) = rc else {
        println!("cargo:warning=resource compiler not found, skipping Windows icon embedding");
        return;
    };

    let res_path = format!("{out_dir}/resource.res");
    let mut command = std::process::Command::new(&rc.path);
    match rc.kind {
        ResourceCompilerKind::Llvm => {
            command
                .arg("-no-preprocess")
                .arg(&rc_path)
                .arg("/FO")
                .arg(&res_path);
        }
        ResourceCompilerKind::Microsoft => {
            command
                .arg("/nologo")
                .arg(format!("/fo{res_path}"))
                .arg(&rc_path);
        }
    }
    let status = match command.status() {
        Ok(status) => status,
        Err(error) => {
            println!(
                "cargo:warning=failed to run resource compiler {}: {error}; exe will not include icon metadata",
                rc.path
            );
            return;
        }
    };

    if status.success() {
        println!("cargo:rustc-link-arg={res_path}");
    } else {
        println!("cargo:warning=resource compilation failed, exe will not include icon metadata");
    }
}

// Build identity (PRD §34/§36). Commit resolution order: GITHUB_SHA (CI,
// authoritative clean checkout) -> `git rev-parse HEAD` -> "unknown". Failure
// to resolve must never fail the build.
fn generate_build_info() {
    let (full_commit, dirty) = resolve_commit();
    let short_commit = if full_commit == "unknown" {
        full_commit.clone()
    } else {
        full_commit.chars().take(7).collect()
    };

    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default();
    let timestamp = format_rfc3339_utc(now.as_secs() as i64);

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR is set by cargo");
    let path = format!("{out_dir}/build_info.rs");
    std::fs::write(
        &path,
        format!(
            "// @generated by build.rs; do not edit.\n\
             pub const FULL_COMMIT: &str = \"{full_commit}\";\n\
             pub const SHORT_COMMIT: &str = \"{short_commit}\";\n\
             pub const COMMIT_DIRTY: bool = {dirty};\n\
             pub const BUILD_TIMESTAMP: &str = \"{timestamp}\";\n"
        ),
    )
    .expect("failed to write generated build_info.rs");

    println!("cargo:rerun-if-env-changed=GITHUB_SHA");
    // Keep the embedded commit fresh across local incremental builds: HEAD
    // changes on branch switches, the ref file on commits to the current
    // branch (packed refs fall back to a build.rs touch). Missing paths are
    // ignored by cargo, so this stays harmless outside a git checkout.
    println!("cargo:rerun-if-changed=.git/HEAD");
    if let Ok(head_ref) = std::fs::read_to_string(".git/HEAD")
        && let Some(reference) = head_ref.trim().strip_prefix("ref: ")
    {
        println!("cargo:rerun-if-changed=.git/{reference}");
    }
}

fn resolve_commit() -> (String, bool) {
    if let Ok(sha) = std::env::var("GITHUB_SHA") {
        let sha = sha.trim().to_ascii_lowercase();
        if is_full_sha(&sha) {
            return (sha, false);
        }
    }

    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap_or_else(|_| ".".into());
    let rev_parse = std::process::Command::new("git")
        .args(["rev-parse", "HEAD"])
        .current_dir(&manifest_dir)
        .output();
    if let Ok(output) = rev_parse
        && output.status.success()
    {
        let sha = String::from_utf8_lossy(&output.stdout)
            .trim()
            .to_ascii_lowercase();
        if is_full_sha(&sha) {
            // Dirty means tracked files carry uncommitted modifications
            // (working tree or index); untracked files do not count.
            let status = std::process::Command::new("git")
                .args(["status", "--porcelain", "--untracked-files=no"])
                .current_dir(&manifest_dir)
                .output();
            let dirty = status
                .map(|out| out.status.success() && !out.stdout.is_empty())
                .unwrap_or(false);
            return (sha, dirty);
        }
    }

    ("unknown".to_owned(), false)
}

fn is_full_sha(value: &str) -> bool {
    value.len() == 40 && value.chars().all(|ch| ch.is_ascii_hexdigit())
}

fn format_rfc3339_utc(secs: i64) -> String {
    let days = secs.div_euclid(86400);
    let time = secs.rem_euclid(86400);
    let (year, month, day) = days_to_ymd(days);
    format!(
        "{year:04}-{month:02}-{day:02}T{:02}:{:02}:{:02}Z",
        time / 3600,
        (time % 3600) / 60,
        time % 60
    )
}

#[derive(Clone, Copy)]
enum ResourceCompilerKind {
    Llvm,
    Microsoft,
}

struct ResourceCompiler {
    path: String,
    kind: ResourceCompilerKind,
}

impl ResourceCompiler {
    fn from_path(path: String, fallback_kind: ResourceCompilerKind) -> Self {
        let is_llvm = std::path::Path::new(&path)
            .file_name()
            .and_then(|name| name.to_str())
            .is_some_and(|name| {
                name.eq_ignore_ascii_case("llvm-rc")
                    || name.eq_ignore_ascii_case("llvm-rc.exe")
                    || name.eq_ignore_ascii_case("llvm-rc-20")
                    || name.eq_ignore_ascii_case("llvm-rc-20.exe")
            });
        Self {
            path,
            kind: if is_llvm {
                ResourceCompilerKind::Llvm
            } else {
                fallback_kind
            },
        }
    }
}

fn find_windows_sdk_rc() -> Option<ResourceCompiler> {
    let kits_root = std::env::var_os("ProgramFiles(x86)")
        .map(std::path::PathBuf::from)
        .unwrap_or_else(|| std::path::PathBuf::from(r"C:\Program Files (x86)"))
        .join("Windows Kits")
        .join("10")
        .join("bin");
    let arch = match std::env::var("CARGO_CFG_TARGET_ARCH").as_deref() {
        Ok("aarch64") => "arm64",
        Ok("x86") => "x86",
        _ => "x64",
    };

    let mut versions = std::fs::read_dir(kits_root)
        .ok()?
        .flatten()
        .collect::<Vec<_>>();
    versions.sort_by_key(|entry| std::cmp::Reverse(entry.file_name()));
    versions.into_iter().find_map(|entry| {
        let path = entry.path().join(arch).join("rc.exe");
        path.is_file().then(|| {
            ResourceCompiler::from_path(
                path.to_string_lossy().into_owned(),
                ResourceCompilerKind::Microsoft,
            )
        })
    })
}

/// Git Bash's `which.exe` (first on PATH on GitHub Windows runners) reports
/// MSYS-rooted paths like `/c/Program Files/LLVM/bin/llvm-rc` — without the
/// `.exe` suffix — which the Windows loader cannot spawn and which `is_file`
/// does not resolve. Translate those to `C:/...`, retrying with the suffix,
/// and reject the lookup otherwise.
fn normalize_which_path(found: &str) -> Option<String> {
    let found = found.trim();
    if !found.starts_with('/') {
        return Some(found.to_owned());
    }
    let bytes = found.as_bytes();
    if bytes.len() >= 3 && bytes[1] == b'/' && bytes[0].is_ascii_alphabetic() {
        let plain = format!("{}:{}", bytes[0] as char, &found[2..]);
        if std::path::Path::new(&plain).is_file() {
            return Some(plain);
        }
        let with_exe = format!("{plain}.exe");
        if std::path::Path::new(&with_exe).is_file() {
            return Some(with_exe);
        }
    }
    None
}

fn days_to_ymd(mut days: i64) -> (u32, u32, u32) {
    let mut y = 1970i64;
    loop {
        let dy = if y % 4 == 0 && (y % 100 != 0 || y % 400 == 0) {
            366
        } else {
            365
        };
        if days < dy {
            break;
        }
        days -= dy;
        y += 1;
    }
    let leap = y % 4 == 0 && (y % 100 != 0 || y % 400 == 0);
    let md: &[u32] = if leap {
        &[31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    } else {
        &[31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    };
    let mut m = 0u32;
    for (i, &d) in md.iter().enumerate() {
        if days < d as i64 {
            m = i as u32 + 1;
            break;
        }
        days -= d as i64;
    }
    if m == 0 {
        m = 12;
    }
    (y as u32, m, days as u32 + 1)
}

fn which(name: &str) -> Option<String> {
    // `where.exe` reports native Windows paths, while `which` (Git Bash on CI
    // runners) answers with MSYS-rooted paths and possibly several matches.
    if cfg!(windows)
        && let Some(found) = locate_with("where", name)
    {
        return Some(found);
    }
    locate_with("which", name)
}

fn locate_with(tool: &str, name: &str) -> Option<String> {
    let output = std::process::Command::new(tool).arg(name).output().ok()?;
    if !output.status.success() {
        return None;
    }
    String::from_utf8_lossy(&output.stdout)
        .lines()
        .map(str::trim)
        .find(|line| !line.is_empty())
        .map(str::to_owned)
}
