//! Compile-time build identity (PRD §34/§36).
//!
//! Commit data is generated by `build.rs` into `OUT_DIR/build_info.rs`
//! (`GITHUB_SHA` -> `git rev-parse HEAD` -> `unknown`). A missing git
//! environment must never break the build or break version display.

include!(concat!(env!("OUT_DIR"), "/build_info.rs"));

pub fn version() -> &'static str {
    env!("CARGO_PKG_VERSION")
}

pub fn full_commit() -> &'static str {
    FULL_COMMIT
}

/// Seven-character short commit, or `unknown` when git was unavailable.
pub fn short_commit() -> &'static str {
    SHORT_COMMIT
}

pub fn commit_dirty() -> bool {
    COMMIT_DIRTY
}

pub fn build_timestamp() -> &'static str {
    BUILD_TIMESTAMP
}

/// `a13f72c` or `a13f72c-dirty` for local builds with uncommitted changes.
pub fn display_commit() -> String {
    if COMMIT_DIRTY {
        format!("{}-dirty", short_commit())
    } else {
        short_commit().to_owned()
    }
}

/// Diagnostic form used outside the main UI: `0.9.0 (a13f72c-dirty)`.
pub fn diagnostic_version() -> String {
    format!("{} ({})", version(), display_commit())
}

/// `LogcatX 0.9.0 (abcdef1)` — the `--version` output (PRD §48).
pub fn summary() -> String {
    format!("LogcatX {}", diagnostic_version())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn short_commit_is_seven_chars_or_unknown() {
        assert!(SHORT_COMMIT == "unknown" || SHORT_COMMIT.len() == 7);
        assert!(FULL_COMMIT == "unknown" || FULL_COMMIT.len() == 40);
    }

    #[test]
    fn diagnostic_version_shape() {
        let version = diagnostic_version();
        assert!(version.starts_with(concat!(env!("CARGO_PKG_VERSION"), " (")));
        assert!(version.ends_with(')'));
        if COMMIT_DIRTY {
            assert!(version.ends_with("-dirty)"));
        } else {
            assert!(!version.contains("dirty"));
        }
    }

    #[test]
    fn summary_shape() {
        let expected = format!("LogcatX {}", diagnostic_version());
        assert_eq!(summary(), expected);
    }

    #[test]
    fn build_timestamp_is_rfc3339_utc() {
        let ts = BUILD_TIMESTAMP;
        // 2026-09-22T12:34:56Z
        assert_eq!(ts.len(), 20, "unexpected timestamp: {ts}");
        assert_eq!(&ts[4..5], "-");
        assert_eq!(&ts[10..11], "T");
        assert_eq!(&ts[19..], "Z");
    }
}
